ALTER TYPE "CompetitionPickType" ADD VALUE IF NOT EXISTS 'QUARTER_FINALIST';
ALTER TYPE "CompetitionPickType" ADD VALUE IF NOT EXISTS 'SEMI_FINALIST';
ALTER TYPE "CompetitionPickType" ADD VALUE IF NOT EXISTS 'FINALIST';

ALTER TABLE "Rule" ADD COLUMN IF NOT EXISTS "enableCompetitionQuarterFinalist" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Rule" ADD COLUMN IF NOT EXISTS "pointsCompetitionQuarterFinalist" INTEGER NOT NULL DEFAULT 8;
ALTER TABLE "Rule" ADD COLUMN IF NOT EXISTS "enableCompetitionSemiFinalist" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Rule" ADD COLUMN IF NOT EXISTS "pointsCompetitionSemiFinalist" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "Rule" ADD COLUMN IF NOT EXISTS "enableCompetitionFinalist" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Rule" ADD COLUMN IF NOT EXISTS "pointsCompetitionFinalist" INTEGER NOT NULL DEFAULT 12;

ALTER TABLE "SuperSetting" ADD COLUMN IF NOT EXISTS "competitionType" TEXT NOT NULL DEFAULT 'LEAGUE';
